### PR TITLE
Milestone-2: Friendships v1

### PR DESCRIPTION
**Pull request by emmanuellekamwa**
In this project, I have created a model with the associations with all the features requested for friendship and I have written unit tests for that.

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
---------------
Hello, @emmanuellekamwa You are doing an amazing job in this milestone :muscle: 
However, there a few changes to make to complete this milestone :hammer_and_wrench: see them below :eyes: :point_down: 
-------------------

- [ ] Please improve your Readme file. 
- On section `Getting Started`section there are not steps on how to clone the repository. Please add one. 
- You have this on `run tests` section.

Screenshot from 2021-03-30 15-52-44

Please delete it that makes look your readme unprofessional. 
- [OPTIONAL] put an image of the current project. 

- [ ] I cannot run `rails db:migrate`. I got this error.

Screenshot from 2021-03-30 16-06-18
You have a migration table that doesn't exist. 
Screenshot from 2021-03-30 16-12-09
This migration is causing the error. 
- [x] I cannot send a friend request. 

send_invitation

- [ ] For the above error. I cannot accept or reject the friendship.
- [ ] I cannot run the test locally. Please fix this. 
--------------------------------
Make the required changes above :point_up_2: and send it again for another review :smile: 
Reachme on SLACK  if you have any questions. 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!!

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi Alix!
Great job so far:clap::clap:. Thank you for updating the readme. So it can look more professional.**
However, we need to make a few changes to get the project approved:muscle:.

**To improve**

- [ ] App Behavior

- User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). When I click on the `invite friends ` link. I get this [error](https://imgur.com/a/B6wr1mD). Please check the friendship migrations and fix any abnormalities.

- User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Also ensure this feature is working.

- User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Also ensure this feature is working.

- There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Also ensure this feature also works.

- Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, the post timeline displays all the posts for the logged-in users. It should only display the current user and its friend's post. Please fix this.

- [ ] Test

- Currently, you only have just three tests. Kindly write tests for the features you implemented. Both unit and integration tests that cover positive and negative test case scenarios.

Make the above required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Emmanuelle Alix** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] In your README file, add a broader description of your project, ¿what is it about?
- [ ] Add integration tests to your project
- [ ] Request friendship isn't working


 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUIRED :writing_hand:

Hello team @emmanuellekamwa You did a pretty good job in this project. 👏🏾 

#### ToHighlight

- [ ] Good job on following the correct GitHub flow ✔️  
- [ ] Your commit messages are well written in the present tense ✔️ 
- [ ] You did add more tests ✔️ 

#### To Improve
- Post timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, the post timeline displays all the posts for the logged-in users. It should only display the current user and its friend's post. Please fix this.
- Like the previous two TSE's mentioned, your `friendship` request is not working. I am still getting the same error as the previous TSE. [Check out how friendships can be implemented in active record](https://smartfunnycool.com/friendships-in-activerecord/)

image

**Kindly refer to the second TSE who gave comments on how this model should work**


That's all :smile: kindly submit another review when done.

_If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me @mimipeshy. I will be happy to help_
Regards
Peris Ndanu

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work making the requested changes. Sending and confirmation of friends request now works as expected. Well done!
We however, have one change to make before we can merge this PR. Logged in users can see posts by users that they are not friends with. This is not supposed to happen. Please fix that.


### Martin Afani
#### Slack: whiz25

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED :green_circle: 
-----------------
Hello again :wave: You work really hard on this project :muscle: 
CONGRATULATIONS!!! :clap: 
--------------
Now you can merge this branch :smile: 
HAPPY CODING!! AND GOOD LUCK WITH THE COMMING ONES :+1: :1st_place_medal: 

Well-Done-Applause

**Pull request merged**
